"""
generate_sql, validate_sql, execute_sql.

Checks are tracked as a flat list spanning every table, each with its
OWN status and retry_count - a failing check for one table must not
block or re-trigger checks for a different table that already passed.

Table/column/related_table for each compiled rule are carried over from
the matching planned check, not regenerated by the LLM - the LLM is
only ever asked for the one thing it's actually deciding: the SQL text.
"""

import re
from typing import TypedDict

from langchain_core.messages import ToolMessage
from langchain.tools import tool, ToolRuntime
from langgraph.types import Command

from config import FORBIDDEN_SQL_KEYWORDS, MAX_RETRIES, get_llm
from state import CompiledRule, DQState
from utils.database import run_query

_GENERATOR_SYSTEM_PROMPT = """You are a SQL generation agent. You write DuckDB SQL
for data quality checks.

For each planned check, write ONE SELECT statement that returns the
rows which VIOLATE the rule. For example, a "not null" check on column
"email" should select the rows where email IS NULL. A uniqueness check
should select the duplicate rows.

Rules:
- SELECT statements only. Never DROP, DELETE, UPDATE, INSERT, ALTER,
  CREATE, TRUNCATE, MERGE, CALL, or REPLACE.
- Reference the table by its exact name, double-quoted.
- One single SELECT statement per check - no semicolons inside it.
- Add "LIMIT 200" to every query.
- If given a previous_error for a check, fix that specific problem.
- This is DuckDB. For regex, use regexp_matches(column, pattern) or ~
  - never REGEXP, which DuckDB does not support.
"""


class _GeneratedRule(TypedDict):
    check_name: str
    sql: str


class _SqlGenerationOutput(TypedDict):
    rules: list[_GeneratedRule]


def _generate(metadata_by_table: dict, checks: list[dict]) -> dict[str, str]:
    """Returns {check_name: sql}."""
    llm = get_llm().with_structured_output(_SqlGenerationOutput)
    result = llm.invoke([
        {"role": "system", "content": _GENERATOR_SYSTEM_PROMPT},
        {"role": "user", "content": (
            f"Metadata for all tables:\n{metadata_by_table}\n"
            f"Checks to write SQL for:\n{checks}\n"
        )},
    ])
    return {rule["check_name"]: rule["sql"] for rule in result["rules"]}


@tool
def generate_sql(runtime: ToolRuntime[None, DQState]) -> Command:
    """Write DuckDB SQL for planned checks that don't have valid SQL
    yet. First call: writes SQL for every planned check. Later calls:
    only regenerates checks marked invalid and still under the retry
    limit; valid checks are left untouched."""
    state = runtime.state
    metadata_by_table = state["metadata_by_table"]
    planned_checks = state["planned_checks"]

    if not metadata_by_table or not planned_checks:
        return Command(update={
            "messages": [ToolMessage(
                content="Cannot generate SQL yet: call create_rule_plan first.",
                tool_call_id=runtime.tool_call_id,
            )],
        })

    compiled_rules = state["compiled_rules"]
    planned_by_name = {c["check_name"]: c for c in planned_checks}

    if not compiled_rules:
        sql_by_name = _generate(metadata_by_table, planned_checks)
        new_rules: list[CompiledRule] = [
            {
                "check_name": name,
                "table": planned_by_name[name]["table"],
                "related_table": planned_by_name[name]["related_table"],
                "column": planned_by_name[name]["column"],
                "sql": sql,
                "status": "pending_validation",
                "validation_error": None,
                "retry_count": 0,
            }
            for name, sql in sql_by_name.items() if name in planned_by_name
        ]
        return Command(update={
            "compiled_rules": new_rules,
            "messages": [ToolMessage(
                content=f"Generated SQL for {len(new_rules)} check(s). Call validate_sql next.",
                tool_call_id=runtime.tool_call_id,
            )],
        })

    fixable = [r for r in compiled_rules if r["status"] == "invalid" and r["retry_count"] < MAX_RETRIES]
    exhausted = [r["check_name"] for r in compiled_rules if r["status"] == "invalid" and r["retry_count"] >= MAX_RETRIES]

    if not fixable:
        return Command(update={
            "messages": [ToolMessage(
                content=(
                    f"No fixable checks remain (exhausted: {exhausted or 'none'}). "
                    "Call execute_sql for the valid checks, then write_report."
                ),
                tool_call_id=runtime.tool_call_id,
            )],
        })

    to_regen = [
        {**planned_by_name[r["check_name"]], "previous_error": r["validation_error"]}
        for r in fixable if r["check_name"] in planned_by_name
    ]
    fixed_sql = _generate(metadata_by_table, to_regen)

    fixable_names = {r["check_name"] for r in fixable}
    updated_rules = []
    for r in compiled_rules:
        if r["check_name"] in fixable_names and r["check_name"] in fixed_sql:
            updated_rules.append({
                **r, "sql": fixed_sql[r["check_name"]], "status": "pending_validation",
                "validation_error": None, "retry_count": r["retry_count"] + 1,
            })
        else:
            updated_rules.append(r)

    return Command(update={
        "compiled_rules": updated_rules,
        "messages": [ToolMessage(
            content=(
                f"Regenerated SQL for {sorted(fixable_names)}. "
                f"{len(exhausted)} check(s) already exhausted retries. "
                f"Call validate_sql next."
            ),
            tool_call_id=runtime.tool_call_id,
        )],
    })


_KEYWORD_PATTERN = re.compile(r"\b(" + "|".join(FORBIDDEN_SQL_KEYWORDS) + r")\b", re.IGNORECASE)


def _validate_one(sql: str) -> str | None:
    cleaned = sql.strip().rstrip(";")
    if not cleaned.upper().startswith("SELECT"):
        return "must be a single SELECT statement"
    if ";" in cleaned:
        return "only one statement is allowed"
    match = _KEYWORD_PATTERN.search(cleaned)
    if match:
        return f"contains forbidden keyword '{match.group(1).upper()}'"
    return None


@tool
def validate_sql(runtime: ToolRuntime[None, DQState]) -> Command:
    """Validate every check whose SQL was just (re)generated. Checks
    already 'valid' or permanently 'invalid' are left untouched."""
    compiled_rules = runtime.state["compiled_rules"]

    updated_rules, newly_valid, newly_invalid = [], 0, 0
    for r in compiled_rules:
        if r["status"] != "pending_validation":
            updated_rules.append(r)
            continue
        error = _validate_one(r["sql"])
        if error is None:
            updated_rules.append({**r, "status": "valid", "validation_error": None})
            newly_valid += 1
        else:
            updated_rules.append({**r, "status": "invalid", "validation_error": error})
            newly_invalid += 1

    still_invalid = [r["check_name"] for r in updated_rules if r["status"] == "invalid"]
    summary = f"{newly_valid} check(s) passed, {newly_invalid} failed." + (
        f" Still invalid: {still_invalid}." if still_invalid else " All checks are now valid."
    )
    return Command(update={
        "compiled_rules": updated_rules,
        "messages": [ToolMessage(content=summary, tool_call_id=runtime.tool_call_id)],
    })


@tool
def execute_sql(runtime: ToolRuntime[None, DQState]) -> Command:
    """Run every check currently 'valid' and not yet executed."""
    compiled_rules = runtime.state["compiled_rules"]
    already_executed = {r["check_name"] for r in runtime.state["execution_results"]}
    to_run = [r for r in compiled_rules if r["status"] == "valid" and r["check_name"] not in already_executed]

    if not to_run:
        return Command(update={
            "messages": [ToolMessage(content="No newly-valid checks to execute.", tool_call_id=runtime.tool_call_id)],
        })

    new_results = []
    for r in to_run:
        outcome = run_query(r["sql"])
        new_results.append({
            "check_name": r["check_name"], "table": r["table"],
            "related_table": r["related_table"], "column": r["column"],
            "sql": r["sql"], "row_count": outcome["row_count"],
        })

    results = runtime.state["execution_results"] + new_results
    violations = sum(1 for r in new_results if r["row_count"] > 0)
    return Command(update={
        "execution_results": results,
        "messages": [ToolMessage(
            content=f"Executed {len(new_results)} check(s); {violations} found violations.",
            tool_call_id=runtime.tool_call_id,
        )],
    })